enqueue:
    default:
        transport:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        consumption:
            receive_timeout: 10000
        client:
            default_queue: 'default'
            traceable_producer: true
            prefix: enqueue
            separator: '.'
            app_name: 'shopping-service'
            router_topic: default
            router_queue: default
            router_processor: null
            redelivered_delay_time: 0
            driver_options: []
        extensions:
            doctrine_ping_connection_extension: false
            doctrine_clear_identity_map_extension: false
            doctrine_odm_clear_identity_map_extension: false
            doctrine_closed_entity_manager_extension: false
            reset_services_extension: false
            signal_extension: false
            reply_extension: true