framework:
  messenger:
    transports:
      product-service:
        options:
          exchange:
            name: ecommerce.product
          queues:
            product-service: ~
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.json_serializer

      inventory-service:
        options:
          exchange:
            name: ecommerce.inventory
          queues:
            inventory-service: ~
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer

      shopping-service:
        options:
          exchange:
            name: ecommerce.shopping
          queues:
            shopping-service: ~
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.json_serializer
