framework:
    messenger:
        enabled: true
        default_bus: command_bus
        buses:
            command_bus:
            query_bus:
        transports:
            rabbitmq:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                failure_transport: failed
            failed:
                dsn: '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
                options:
                    queue: failed_search_messages
