services:
  shopping-service:
    build:
      context: ./shopping-service
      dockerfile: Dockerfile
    volumes:
      - ./shopping-service:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - ecommerce-network
    depends_on:
      - shopping-db
    command: ["php-fpm"]

  shopping-nginx:
    image: nginx:latest
    ports:
      - "8003:80"
    volumes:
      - ./shopping-service:/var/www/html
      - ./shopping-service/docker/nginx/default.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce-network
    depends_on:
      - shopping-service

  shopping-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping
      MYSQL_USER: shopping_user
      MYSQL_PASSWORD: shopping_password
    ports:
      - "3309:3306"
    volumes:
      - ./shopping-service/docker/db-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true

volumes:
  db-data: